### PR TITLE
Add override for libsqlite3-sys

### PR DESCRIPTION
**Pull request by edude03**
Needed this for building a crate (rusqlite), so I added it.

### CODE REVIEW

**Review by psionic-k — APPROVED** [review]
Yep

**Comment by psionic-k** [comment]
@edude03 this organization has the highest standards of expediency and professionalism.  Please mind your pull request.

**Comment by edude03** [comment]
Thanks for merging for me @psionic-k 👍

**Comment by psionic-k** [comment]
@edude03  thank you for thanking me :1st_place_medal:    It's been a hell of a ride.

**Pull request merged**
