### PR TITLE
Update copyright holders to indicate ownership transfer

### PR DESCRIPTION
**Pull request by ebkalderon**
### Changed

* Update `LICENSE` to credit the individual `cargo2nix` developers as copyright holders.

### CODE REVIEW

**Comment by ebkalderon** [comment]
Blocked on #148.

**Comment by ebkalderon** [comment]
Looks like #148 successfully worked around the CI issue! :tada:

**Review by psionic-k — APPROVED** [review]
:shipit:

**Comment by ebkalderon** [comment]
Goodbye, TenX. :wave:

**Pull request merged**
